create table if not exists public.event_discovery_cache (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  variant_key text not null default 'event',
  name text not null,
  discipline_name text not null default '',
  event_date date,
  end_date date,
  start_time text,
  location text not null default '',
  country_code text not null default '',
  target_km numeric,
  source_name text not null default '',
  source_url text not null default '',
  search_text text not null default '',
  raw_event jsonb not null default '{}'::jsonb,
  last_verified_at timestamptz not null default now(),
  expires_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_discovery_cache_provider_event_variant_key unique (provider, provider_event_id, variant_key)
);

create index if not exists event_discovery_cache_search_text_idx
  on public.event_discovery_cache using gin (to_tsvector('simple', search_text));

create index if not exists event_discovery_cache_event_date_idx
  on public.event_discovery_cache (event_date);

create index if not exists event_discovery_cache_expires_at_idx
  on public.event_discovery_cache (expires_at);

alter table public.event_discovery_cache enable row level security;

comment on table public.event_discovery_cache is
  'Server-only cache for public event metadata discovered through authenticated Edge Function calls.';
